language: r
sudo: required

apt_packages:
 - libcurl4-openssl-dev
 - libxml2-dev

r_packages:
  - readr
  - rmarkdown

install:
  - which R
  - Rscript -e 'install.packages("rmarkdown", lib = .libPaths()[1], repos = "http://cran.us.r-project.org")'
  - Rscript -e "library(rmarkdown); rmarkdown:render('analyze.Rmd')"

addons:
  artifacts: true

