language: r
sudo: required

r_binary_packages:
  - rmarkdown
  - knitr

r_packages:
  - readr
  - knitr

install:
  - Rscript -e "library(knitr); knitr::knit2html('analysis.Rmd')"

addons:
  artifacts: true

#r_github_packages:
#  - jimhester/covr