language: r
sudo: required

apt_packages:
 - libcurl4-openssl-dev
 - libxml2-dev

r_binary_packages:
  - rmarkdown
  - dplyr

r_packages:
  - readr

script:
  - export ARTIFACTS_TARGET_PATHS="artifacts/$TRAVIS_REPO_SLUG/"
  - Rscript -e "library(rmarkdown); rmarkdown::render('analyze.Rmd')"


addons:
  artifacts: true

