language: r
sudo: required

apt_packages:
 - libcurl4-openssl-dev
 - libxml2-dev

r_packages:
  - readr
  - rmarkdown
  - knitr

install:
  - Rscript -e "library(knitr); knitr::knit2html('analyze.Rmd')"

addons:
  artifacts: true

#r_github_packages:
#  - jimhester/covr