language: r
sudo: required
apt_packages:
- libcurl4-openssl-dev
- libxml2-dev

r_binary_packages:
- rmarkdown
- dplyr

script:
- Rscript -e "library(rmarkdown); rmarkdown::render('analyze.Rmd')"

addons:
  artifacts:
    debug: true
    target_paths: $TRAVIS_REPO_SLUG
