language: r

sudo: required

apt_packages:
- libcurl4-openssl-dev
- libxml2-dev

r_binary_packages:
- rmarkdown
- dplyr

script:
- Rscript -e "library(rmarkdown); rmarkdown::render('analyze.Rmd')"

deploy:
  provider: s3
  access_key_id: AKIAIZDYBCZNSLOXEQXA
  secret_access_key:
    secure: L0BpVchsPn+KMB2cA1Z2lbsorMYhnmrpAujDyGuDpxEBae5lCy3G3ZJoby4B67jN5Ey69QUKnOqW8ItuXEK3WvbiDIGDxXWwDVgBuerjx1fNkix67urpo9ZUI6+qsUwfkC3Sm5642tLSXIczIsjecCN+S0Acsg+8BtFsdU0QVOwMDs8gpSFek7dvm5m+BZuUuRY8hQKPMHik92AFQV9KBCWDI8/k6jvcrnhWmLnSv07Uryq2bD2OHSMbZU/PYGIJUPCVXfP+Ugd6Tkhy+qizoYfEWCzwA2nWTbN9V7Vw4A9vJOF4YI6NkYKC8AUQZuEPNQsSdUvE57qSLli9aSukOvqwseF7blMi5E6nro8PvQ2cZSv+ioRrh6iITAZnCVoKv61GtEOYKSRZw/I8QteNh1Ah7mwxz8B+e4+7mUBjbOUAA2XOFR26wChZlXKQwCG3SnF2Dz+jin15X5PvyqDNIF1mI1Mgqr/8BguQ4NIJkWqWYlst3PbLU1Iuo8W8hK5MsnPavIsUY7qw4E9YRL4gUFsbzPlIlky1W6qol8DECSPzeRreuuoV3FykEwb9iV9dOC5Qn7OXyuTRddshogXxMX8gJT97C2Ok5s7C+ygznX2RIQDaD7DILxV91WxxGvq+E/gJEZvw1o+ojXkhevC6VgwP/ZED0+T9hfUv9mcH8r8=
  bucket: rmarkdown
  upload-dir: Andersen-lab-strains
  acl: ''
  on:
    repo: AndersenLab/Andersen-Lab-Strains
