language: r
sudo: required

r_binary_packages:
  - rmarkdown
  - knitr

r_packages:
  - readr

install:
  - Rscript -e "rmarkdown::render('analysis.Rmd')"

addons:
  artifacts: true

#r_github_packages:
#  - jimhester/covr