language: r
sudo: required

apt_packages:
 - libcurl4-openssl-dev
 - libxml2-dev

r_packages:
  - readr
  - rmarkdown

script:
  - Rscript -e "library(rmarkdown); rmarkdown:render('analyze.Rmd')"

addons:
  artifacts: true

