---
title: "Andersen Lab Strains"
author: "Dan Cook"
date: "`r Sys.Date()`"
output: 
  html_document:
    theme: united
    toc: yes
  pdf_document: 
    toc: yes
---

```{r, echo = F, warning=FALSE, message=FALSE}
library(readr)
library(tidyr)
library(dplyr)
library(knitr)
library(ggplot2)
library(scales)
library(gdata)
library(waffle)

seqs <- readr::read_tsv("raw/seq.raw.tsv", na = c("","NA","#N/A"))

na_to_0 <- function(x) {
  ifelse(is.na(x), 0, x)
}

summarize_column <- function(colnames) {
       seqs %>%
       dplyr::filter(processed == TRUE) %>%
       dplyr::group_by_(.dots = colnames, "use_in_analysis") %>%
       dplyr::summarize(sum = n()) %>% 
       dplyr::ungroup() %>%
       tidyr::spread(use_in_analysis, sum) %>%
       dplyr::rename("YES" = `TRUE`, "NO" = `FALSE`) %>%
       dplyr::mutate_each(funs(na_to_0), everything()) %>%
       dplyr::mutate(use_rate = YES / (NO + YES))
}

run_count <- summarize_column("run")
lib_count <- summarize_column(c("run","lib"))
strain_count <- summarize_column(c("run","lib","strain","isotype"))

total_strains <- (strain_count %>%
                 dplyr::filter(use_rate > 0) %>%
                 dplyr::distinct(strain) %>%
                 dplyr::ungroup() %>%
                 dplyr::summarize(n = n()))$n

total_isotypes <- (strain_count %>%
                 dplyr::filter(use_rate > 0) %>%
                 dplyr::distinct(isotype) %>%
                 dplyr::ungroup() %>%
                 dplyr::summarize(n = n()))$n

total_sequences <- (dplyr::filter(seqs, use_in_analysis == TRUE) %>%
                   dplyr::summarize(n_reads = comma(sum(as.numeric(reads), na.rm = TRUE))))$n_reads

total_fastq_pairs <- nrow(dplyr::filter(seqs, use_in_analysis == TRUE))

total_file_size <- dplyr::filter(seqs, use_in_analysis == TRUE) %>%
                    dplyr::mutate(filesize = fq1_size + fq2_size) %>% 
                    dplyr::summarize(humanReadable(sum(as.numeric(filesize))))
        

libraries <- dplyr::group_by(seqs, lib) %>% summarize(sum = n())

```

#### Statistics

* __Total Strains__: `r total_strains`
* __Total Isotypes__: `r total_isotypes`
* __Total Sequences__: `r total_sequences`
* __Total Fastq Pairs__: `r total_fastq_pairs`
* __Total File Size__: `r total_file_size`

### Runs

`r kable(run_count)`

```{r, echo = F}

runs <- table(c(dplyr::filter(seqs, use_in_analysis == TRUE) %>% dplyr::select(run)))

colors=c("#882E72", "#B178A6", "#D6C1DE", "#1965B0", "#5289C7", "#7BAFDE", "#4EB265", "#90C987", "#CAE0AB", "#F7EE55", "#F6C141", "#F1932D", "#E8601C", "#DC050C")

waffle(runs, rows=30, size=0.5, 
       colors=rev(colors))
```
n = `r sum(runs)`


### Libraries

`r kable(lib_count)`

```{r generate isotype file, echo = F}

# Output clean seqs file
analysis_seqs <- dplyr::filter(seqs, use_in_analysis == T) %>%
                 dplyr::arrange(run, lib, isotype, strain)
readr::write_tsv(analysis_seqs, "processed/seqs.tsv")

isotypes <- seqs %>% 
  dplyr::select(isotype) %>%
  dplyr::filter(!is.na(isotype)) %>%
  dplyr::distinct() %>%
  dplyr::arrange(isotype)

isotype_strain <- seqs %>% 
  dplyr::select(isotype, strain) %>%
  dplyr::filter(!is.na(isotype)) %>%
  dplyr::distinct() %>%
  dplyr::arrange(isotype)

readr::write_tsv(isotypes, "processed/isotypes.tsv")
readr::write_tsv(isotype_strain, "processed/isotype_strain.tsv")

# Generate Sample File
sample_file <- dplyr::filter(seqs, use_in_analysis == T) %>%                  dplyr::select(fq1, fq2, readgroup, isotype) %>%                   tidyr::separate(readgroup, into = c("RUN", "LB", "STRAIN"), extra = "drop", remove = F) %>%
  dplyr::mutate(PL = "") %>%
  dplyr::select(FQ1 = fq1, FQ2 = fq2, ID = readgroup, LB, SM = isotype, PL) 

readr::write_tsv(sample_file, "processed/sample_file.tsv")

```

