---
title: "Concordance Analysis"
author: "Dan Cook"
date: "`r Sys.Date()`"
output: 
  html_document:
    theme: united
    toc: yes
  pdf_document: 
    toc: yes
---

```{r setup}
library(gplots)
library(ggplot2)
library(tidyr)
library(dplyr)


```

### Concordance - FASTQ

```{r concordance_fastq, fig.width = 20, fig.height = 20, echo = F}

threshold <- 0.9993


stack_list <- function(x) {
  if (is.null(names(x)) == T) {
    names(x) <- as.character(1:length(x))
  }
  stack(x)
}

strain_isotype <- readr::read_tsv("processed/strain_isotype.tsv")


con <- readr::read_tsv("raw/concordance_fastq.tsv", skip = 1, col_names = c("sample_i", "sample_j", "discordance", "number_of_sites")) %>%
      dplyr::mutate(concordance = 1-(discordance/number_of_sites)) %>%
      tidyr::separate(sample_i, sep = "-", into = c("i_run", "i_lib", "i_strain"), extra = "drop", remove = F) %>%
      tidyr::separate(sample_j, sep = "-", into = c("j_run", "j_lib", "j_strain"), extra = "drop", remove = F) %>%
      dplyr::left_join(strain_isotype, by = c("i_strain" = "strain")) %>%
      dplyr::rename(i_isotype = isotype) %>%
      dplyr::left_join(strain_isotype, by = c("j_strain" = "strain")) %>%
      dplyr::rename(j_isotype = isotype) %>%
      dplyr::mutate(isotype = ifelse(i_isotype == j_isotype, TRUE, FALSE)) %>%
      dplyr::mutate(same_strain = ifelse(i_strain == j_strain, TRUE, FALSE)) %>%
      dplyr::mutate(threshold = threshold) %>%
      dplyr::filter(!is.na(isotype))

strain_list <- unique(strain_isotype$strain)

my_palette  <- colorRampPalette(c("blue","green","yellow","red"))(n = 399)
col_breaks = c(seq(0,90,length=100), # blue
seq(90,99,length=100),  # Green
seq(99,99.93,length=100), # for Yellow
seq(99.93,100,length=100)) # for Red


# Draw heatmaps for every strain
results <- lapply(strain_list[1:10], function(x) {
  
  strain_heatmap <- dplyr::filter(con, i_strain == x | j_strain == x) %>%
                    dplyr::arrange(desc(concordance)) %>% 
                    dplyr::mutate(rn = row_number()) %>%
                    dplyr::filter(isotype == TRUE | rn <= 30) %>%
                    dplyr::select(sample_i, sample_j, concordance)
  
  strain_switched <- strain_heatmap
  strain_switched[,c("sample_j","sample_i","concordance")] <- strain_heatmap[,c("sample_i","sample_j", "concordance")]
  
  m <- dplyr::bind_rows(strain_heatmap, strain_switched) %>%
  tidyr::spread(sample_i, concordance) %>%
  replace(is.na(.), 1)
  
  row.names(m) <- m$sample_j
  
  m <- dplyr::select(m, -sample_j) %>%
  as.matrix()
  
  heatmap.2(m*100,
    cellnote = round(m*100,3),  # same data set for cell labels
    notecex=3,
    symm=TRUE,
    dendrogram = c("row"),
    main = x, # heat map title
    notecol="black",      # change font color of cell labels to black
    trace="both",
    tracecol="#00000025", 
    key=FALSE,
    lwid=c(1, 10 ),
    lhei=c(1, 10),
    breaks=col_breaks,# turns off trace lines inside the heat map
    margins=c(10,10),     # widens margins around plot
    col=my_palette)
})


```
